apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: k3s-istio-config
spec:
  # Use default profile for k3s
  profile: default
  
  # Component configuration
  components:
    # Pilot configuration with resource limits for k3s
    pilot:
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
    
    # Ingress Gateway configuration
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
    
    # Egress Gateway (disabled for k3s)
    egressGateways:
      - name: istio-egressgateway
        enabled: false
  
  # Global mesh configuration
  meshConfig:
    # Trust domain for k3s
    trustDomain: cluster.local
    
    # Basic configuration for k3s
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      
  # Values for fine-tuning
  values:
    global:
      # Optimize for k3s resource constraints
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      
      # Configure for k3s service mesh
      meshID: mesh1
      network: network1 