# FastAgent Configuration for XGBoost MCP Server
# This configuration connects to the XGBoost MCP server running in Docker

# MCP Server Configuration
mcp:
  servers:
    # XGBoost MCP Server (running in Docker)
    xgboost:
      transport: http
      url: http://localhost:8000/mcp
      description: "XGBoost machine learning server for model training and predictions"
      
    # Filesystem server for data handling
    filesystem:
      command: "python"
      args: ["filesystem_server.py"]
      description: "Filesystem access for data files and ML datasets"
      
    # Optional: Add memory server for agent state
    memory:
      command: "uvx"
      args: ["mcp-server-memory"]
      description: "Memory server for storing agent state and results"

# Default Model Configuration
defaults:
  model: "claude-3-5-sonnet-20241022"  # Default model for agents
  temperature: 0.7
  max_tokens: 4000

# Agent-specific model overrides
models:
  data_analyst:
    model: "claude-3-5-sonnet-20241022"
    temperature: 0.3  # Lower temperature for analytical tasks
    max_tokens: 6000
  
  model_trainer:
    model: "claude-3-5-sonnet-20241022"
    temperature: 0.5
    max_tokens: 4000
  
  orchestrator:
    model: "claude-3-opus-20240229"  # Use Opus for complex planning
    temperature: 0.8  # Higher temperature for creative planning
    max_tokens: 8000

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Agent Timeouts
timeouts:
  agent_response: 60  # seconds
  mcp_tool_call: 30   # seconds 